from crewai.agents.agent_adapters.openai_agents.openai_agent_tool_adapter import OpenAIAgentToolAdapter as CrewAIOpenAIAgentToolAdapter

# Re-export CrewAI's OpenAIAgentToolAdapter
OpenAIAgentToolAdapter = CrewAIOpenAIAgentToolAdapter
